// Mock data cho testing UI/UX
export const mockStations = [
  {
    id: "ST001",
    name: "Trạm Sạc EV Central Plaza",
    address: "123 Nguyễn Văn Linh, Quận 7, TP.HCM",
    isActive: true,
    status: "available",
    establishedTime: "2023-01-15T00:00:00Z",
    numberOfPosts: 6,
    totalSlots: 6,
    availableSlots: 4,
    distance: "0.5 km",
    power: "450 kW",
    type: "AC/DC",
    openHours: "24/7",
    rating: 4.5,
    reviewCount: 128,
    totalBookings: 15,
    amenities: ["WiFi", "Cafe", "Parking", "Security"],
    chargingPosts: []
  },
  {
    id: "ST002", 
    name: "VinFast Station District 1",
    address: "456 Lê Lợi, Quận 1, TP.HCM",
    isActive: true,
    status: "available",
    establishedTime: "2023-03-20T00:00:00Z",
    numberOfPosts: 4,
    totalSlots: 4,
    availableSlots: 2,
    distance: "1.2 km",
    power: "300 kW", 
    type: "DC Fast",
    openHours: "06:00 - 22:00",
    rating: 4.8,
    reviewCount: 95,
    totalBookings: 8,
    amenities: ["WiFi", "Shop", "Security"],
    chargingPosts: []
  },
  {
    id: "ST003",
    name: "GreenCharge Landmark 81",
    address: "720A Điện Biên Phủ, Bình Thạnh, TP.HCM",
    isActive: true,
    status: "busy",
    establishedTime: "2022-11-10T00:00:00Z",
    numberOfPosts: 8,
    totalSlots: 8,
    availableSlots: 1,
    distance: "2.3 km",
    power: "600 kW",
    type: "AC/DC",
    openHours: "24/7",
    rating: 4.2,
    reviewCount: 203,
    totalBookings: 22,
    amenities: ["WiFi", "Cafe", "Shop", "Parking", "Security"],
    chargingPosts: []
  },
  {
    id: "ST004",
    name: "Tesla Supercharger Saigon",
    address: "789 Võ Văn Kiệt, Quận 5, TP.HCM", 
    isActive: false,
    status: "maintenance",
    establishedTime: "2023-07-01T00:00:00Z",
    numberOfPosts: 12,
    totalSlots: 12,
    availableSlots: 0,
    distance: "3.1 km",
    power: "1200 kW",
    type: "DC Fast",
    openHours: "Tạm đóng cửa",
    rating: 4.9,
    reviewCount: 67,
    totalBookings: 0,
    amenities: ["WiFi", "Shop"],
    chargingPosts: []
  },
  {
    id: "ST005",
    name: "EVN Charging Hub Bitexco",
    address: "2 Hải Triều, Quận 1, TP.HCM",
    isActive: true,
    status: "available", 
    establishedTime: "2023-05-12T00:00:00Z",
    numberOfPosts: 3,
    totalSlots: 3,
    availableSlots: 3,
    distance: "1.8 km",
    power: "165 kW",
    type: "AC/DC",
    openHours: "07:00 - 19:00",
    rating: 4.0,
    reviewCount: 34,
    totalBookings: 3,
    amenities: ["WiFi", "Parking"],
    chargingPosts: []
  }
];

export const mockChargingPosts = {
  "ST001": [
    {
      id: "CP001-1",
      isActive: true,
      maxPower: 150,
      chargingFeePerKWh: 4500,
      powerDisplay: "150 kW",
      feeDisplay: "4,500 VNĐ/kWh",
      status: "available",
      isAvailable: true,
      supportedTypes: ["DC Fast", "CCS2"],
      currentSession: null
    },
    {
      id: "CP001-2", 
      isActive: true,
      maxPower: 50,
      chargingFeePerKWh: 3200,
      powerDisplay: "50 kW",
      feeDisplay: "3,200 VNĐ/kWh",
      status: "busy",
      isAvailable: false,
      supportedTypes: ["AC", "Type 2"],
      currentSession: { userId: "user123", startTime: "2024-10-08T10:30:00Z" }
    },
    {
      id: "CP001-3",
      isActive: true,
      maxPower: 22,
      chargingFeePerKWh: 2800,
      powerDisplay: "22 kW",
      feeDisplay: "2,800 VNĐ/kWh", 
      status: "available",
      isAvailable: true,
      supportedTypes: ["AC", "Type 1"],
      currentSession: null
    }
  ],
  "ST002": [
    {
      id: "CP002-1",
      isActive: true,
      maxPower: 120,
      chargingFeePerKWh: 4200,
      powerDisplay: "120 kW", 
      feeDisplay: "4,200 VNĐ/kWh",
      status: "busy",
      isAvailable: false,
      supportedTypes: ["DC Fast", "CHAdeMO"],
      currentSession: { userId: "user456", startTime: "2024-10-08T09:15:00Z" }
    },
    {
      id: "CP002-2",
      isActive: true,
      maxPower: 120,
      chargingFeePerKWh: 4200,
      powerDisplay: "120 kW",
      feeDisplay: "4,200 VNĐ/kWh",
      status: "busy", 
      isAvailable: false,
      supportedTypes: ["DC Fast", "CCS2"],
      currentSession: { userId: "user789", startTime: "2024-10-08T11:00:00Z" }
    }
  ]
};